numerical_params:
  num_neighbors: 2
  num_time_steps: 12000
  time_increment: 0.001
  domain:
    start: 0
    end: 1
  
weight_function:
  type: "default"

input_data:
  path: "data/equally_spaced.txt"

equation_params:
  d: 0.02          # diffusion coefficient (from paper)
  a: 1.0           # reaction rate (from paper)
  p: 1.0           # growth rate exponent (from paper)
  initial_condition: "0.35 + 0.3*np.cos(np.pi*x)"  # initial concentration
  # initial_condition: "4*np.pi"